server:
  name: ClusterEye
grpc:
  address: :50051
http:
  address: :8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: Dkjf334utre1
  dbname: clustereye
  sslmode: disable

influxdb:
  enabled: true
  url: "http://localhost:8086"
  token: "u20NMomO7Sq1pU13BRT0pPT6kn9qT3D-pFp7mVgvRkDswlGicF4oK3PbbIV9W96KwIIU-xoiN2BOzPlfLs7Zjw=="
  organization: "clustereye"
  bucket: "clustereye"
  batch_size: 100
  flush_interval: "10s"
