-- postgres_conninfo tablosunu oluştur
CREATE TABLE IF NOT EXISTS postgres_conninfo (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nodename varchar UNIQUE NOT NULL,
	clustername varchar NULL,
	username varchar NULL,
	"password" varchar NULL,
	send_diskalert bool DEFAULT true NULL,
	silence_until timestamp NULL,
	CONSTRAINT postgres_conninfo_pkey PRIMARY KEY (id)
); 