// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/agent/agent.proto

package agent

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Auth          bool                   `protobuf:"varint,6,opt,name=auth,proto3" json:"auth,omitempty"`
	Test          string                 `protobuf:"bytes,7,opt,name=test,proto3" json:"test,omitempty"`
	PostgresUser  string                 `protobuf:"bytes,8,opt,name=postgres_user,json=postgresUser,proto3" json:"postgres_user,omitempty"`
	PostgresPass  string                 `protobuf:"bytes,9,opt,name=postgres_pass,json=postgresPass,proto3" json:"postgres_pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pkg_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentInfo) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *AgentInfo) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

func (x *AgentInfo) GetPostgresUser() string {
	if x != nil {
		return x.PostgresUser
	}
	return ""
}

func (x *AgentInfo) GetPostgresPass() string {
	if x != nil {
		return x.PostgresPass
	}
	return ""
}

type PostgresInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterName       string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip                string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname          string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeStatus        string                 `protobuf:"bytes,4,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	PgVersion         string                 `protobuf:"bytes,5,opt,name=pg_version,json=pgVersion,proto3" json:"pg_version,omitempty"`
	Location          string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	PgBouncerStatus   string                 `protobuf:"bytes,7,opt,name=pg_bouncer_status,json=pgBouncerStatus,proto3" json:"pg_bouncer_status,omitempty"`
	PgServiceStatus   string                 `protobuf:"bytes,8,opt,name=pg_service_status,json=pgServiceStatus,proto3" json:"pg_service_status,omitempty"`
	ReplicationLagSec int64                  `protobuf:"varint,9,opt,name=replication_lag_sec,json=replicationLagSec,proto3" json:"replication_lag_sec,omitempty"`
	FreeDisk          string                 `protobuf:"bytes,10,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	FdPercent         int32                  `protobuf:"varint,11,opt,name=fd_percent,json=fdPercent,proto3" json:"fd_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostgresInfo) Reset() {
	*x = PostgresInfo{}
	mi := &file_pkg_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfo) ProtoMessage() {}

func (x *PostgresInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfo.ProtoReflect.Descriptor instead.
func (*PostgresInfo) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *PostgresInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PostgresInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PostgresInfo) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *PostgresInfo) GetPgVersion() string {
	if x != nil {
		return x.PgVersion
	}
	return ""
}

func (x *PostgresInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PostgresInfo) GetPgBouncerStatus() string {
	if x != nil {
		return x.PgBouncerStatus
	}
	return ""
}

func (x *PostgresInfo) GetPgServiceStatus() string {
	if x != nil {
		return x.PgServiceStatus
	}
	return ""
}

func (x *PostgresInfo) GetReplicationLagSec() int64 {
	if x != nil {
		return x.ReplicationLagSec
	}
	return 0
}

func (x *PostgresInfo) GetFreeDisk() string {
	if x != nil {
		return x.FreeDisk
	}
	return ""
}

func (x *PostgresInfo) GetFdPercent() int32 {
	if x != nil {
		return x.FdPercent
	}
	return 0
}

// MongoDB bilgileri için mesaj tanımı
type MongoInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterName       string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip                string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname          string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeStatus        string                 `protobuf:"bytes,4,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	MongoVersion      string                 `protobuf:"bytes,5,opt,name=mongo_version,json=mongoVersion,proto3" json:"mongo_version,omitempty"`
	Location          string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	MongoStatus       string                 `protobuf:"bytes,7,opt,name=mongo_status,json=mongoStatus,proto3" json:"mongo_status,omitempty"`
	ReplicaSetName    string                 `protobuf:"bytes,8,opt,name=replica_set_name,json=replicaSetName,proto3" json:"replica_set_name,omitempty"`
	ReplicationLagSec int64                  `protobuf:"varint,9,opt,name=replication_lag_sec,json=replicationLagSec,proto3" json:"replication_lag_sec,omitempty"`
	FreeDisk          string                 `protobuf:"bytes,10,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	FdPercent         int32                  `protobuf:"varint,11,opt,name=fd_percent,json=fdPercent,proto3" json:"fd_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MongoInfo) Reset() {
	*x = MongoInfo{}
	mi := &file_pkg_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoInfo) ProtoMessage() {}

func (x *MongoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoInfo.ProtoReflect.Descriptor instead.
func (*MongoInfo) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *MongoInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *MongoInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MongoInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MongoInfo) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *MongoInfo) GetMongoVersion() string {
	if x != nil {
		return x.MongoVersion
	}
	return ""
}

func (x *MongoInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *MongoInfo) GetMongoStatus() string {
	if x != nil {
		return x.MongoStatus
	}
	return ""
}

func (x *MongoInfo) GetReplicaSetName() string {
	if x != nil {
		return x.ReplicaSetName
	}
	return ""
}

func (x *MongoInfo) GetReplicationLagSec() int64 {
	if x != nil {
		return x.ReplicationLagSec
	}
	return 0
}

func (x *MongoInfo) GetFreeDisk() string {
	if x != nil {
		return x.FreeDisk
	}
	return ""
}

func (x *MongoInfo) GetFdPercent() int32 {
	if x != nil {
		return x.FdPercent
	}
	return 0
}

type AlarmCondition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metric          string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`                                           // "postgres_status", "memory_usage"
	Operator        string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`                                       // ">", "<", "="
	Threshold       string                 `protobuf:"bytes,3,opt,name=threshold,proto3" json:"threshold,omitempty"`                                     // "90", "FAIL"
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Süreklilik gerektiren koşullar için
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlarmCondition) Reset() {
	*x = AlarmCondition{}
	mi := &file_pkg_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmCondition) ProtoMessage() {}

func (x *AlarmCondition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmCondition.ProtoReflect.Descriptor instead.
func (*AlarmCondition) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AlarmCondition) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AlarmCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *AlarmCondition) GetThreshold() string {
	if x != nil {
		return x.Threshold
	}
	return ""
}

func (x *AlarmCondition) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type AlarmConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"` // "critical", "warning", "info"
	Condition     *AlarmCondition        `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Channels      []string               `protobuf:"bytes,7,rep,name=channels,proto3" json:"channels,omitempty"` // "slack", "email"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmConfiguration) Reset() {
	*x = AlarmConfiguration{}
	mi := &file_pkg_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmConfiguration) ProtoMessage() {}

func (x *AlarmConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmConfiguration.ProtoReflect.Descriptor instead.
func (*AlarmConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AlarmConfiguration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlarmConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlarmConfiguration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AlarmConfiguration) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlarmConfiguration) GetCondition() *AlarmCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *AlarmConfiguration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlarmConfiguration) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type AlarmEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlarmId       string                 `protobuf:"bytes,2,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "triggered", "resolved"
	MetricName    string                 `protobuf:"bytes,5,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricValue   string                 `protobuf:"bytes,6,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmEvent) Reset() {
	*x = AlarmEvent{}
	mi := &file_pkg_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmEvent) ProtoMessage() {}

func (x *AlarmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmEvent.ProtoReflect.Descriptor instead.
func (*AlarmEvent) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AlarmEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlarmEvent) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *AlarmEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AlarmEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlarmEvent) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *AlarmEvent) GetMetricValue() string {
	if x != nil {
		return x.MetricValue
	}
	return ""
}

func (x *AlarmEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlarmEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AlarmEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_pkg_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Query) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *Query) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Result        *any1.Any              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_pkg_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetResult() *any1.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pkg_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegistrationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResult) Reset() {
	*x = RegistrationResult{}
	mi := &file_pkg_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResult) ProtoMessage() {}

func (x *RegistrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResult.ProtoReflect.Descriptor instead.
func (*RegistrationResult) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RegistrationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent'ın alarm durumunu bildirmesi için
type ReportAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*AlarmEvent          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlarmRequest) Reset() {
	*x = ReportAlarmRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlarmRequest) ProtoMessage() {}

func (x *ReportAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlarmRequest.ProtoReflect.Descriptor instead.
func (*ReportAlarmRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReportAlarmRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportAlarmRequest) GetEvents() []*AlarmEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportAlarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlarmResponse) Reset() {
	*x = ReportAlarmResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlarmResponse) ProtoMessage() {}

func (x *ReportAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlarmResponse.ProtoReflect.Descriptor instead.
func (*ReportAlarmResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ReportAlarmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Sadece agent kaydı için kullanılacak mesajlar
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *RegistrationResult    `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterResponse) GetRegistration() *RegistrationResult {
	if x != nil {
		return x.Registration
	}
	return nil
}

// Query için kullanılacak mesajlar
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *QueryRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *QueryResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *QueryResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// PostgreSQL bilgileri için kullanılacak mesajlar
type PostgresInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostgresInfo  *PostgresInfo          `protobuf:"bytes,1,opt,name=postgres_info,json=postgresInfo,proto3" json:"postgres_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresInfoRequest) Reset() {
	*x = PostgresInfoRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfoRequest) ProtoMessage() {}

func (x *PostgresInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfoRequest.ProtoReflect.Descriptor instead.
func (*PostgresInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *PostgresInfoRequest) GetPostgresInfo() *PostgresInfo {
	if x != nil {
		return x.PostgresInfo
	}
	return nil
}

// MongoDB bilgileri için kullanılacak mesajlar
type MongoInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoInfo     *MongoInfo             `protobuf:"bytes,1,opt,name=mongo_info,json=mongoInfo,proto3" json:"mongo_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoInfoRequest) Reset() {
	*x = MongoInfoRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoInfoRequest) ProtoMessage() {}

func (x *MongoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoInfoRequest.ProtoReflect.Descriptor instead.
func (*MongoInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *MongoInfoRequest) GetMongoInfo() *MongoInfo {
	if x != nil {
		return x.MongoInfo
	}
	return nil
}

type PostgresInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresInfoResponse) Reset() {
	*x = PostgresInfoResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfoResponse) ProtoMessage() {}

func (x *PostgresInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfoResponse.ProtoReflect.Descriptor instead.
func (*PostgresInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *PostgresInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MongoInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoInfoResponse) Reset() {
	*x = MongoInfoResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoInfoResponse) ProtoMessage() {}

func (x *MongoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoInfoResponse.ProtoReflect.Descriptor instead.
func (*MongoInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *MongoInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Genel hata mesajı
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Server'dan agent'a gönderilecek mesajlar
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Query
	//	*ServerMessage_Error
	//	*ServerMessage_Registration
	//	*ServerMessage_MetricsRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pkg_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetQuery() *Query {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetRegistration() *RegistrationResult {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *ServerMessage) GetMetricsRequest() *SystemMetricsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_MetricsRequest); ok {
			return x.MetricsRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Query struct {
	Query *Query `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ServerMessage_Registration struct {
	Registration *RegistrationResult `protobuf:"bytes,3,opt,name=registration,proto3,oneof"`
}

type ServerMessage_MetricsRequest struct {
	MetricsRequest *SystemMetricsRequest `protobuf:"bytes,4,opt,name=metrics_request,json=metricsRequest,proto3,oneof"`
}

func (*ServerMessage_Query) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_Registration) isServerMessage_Payload() {}

func (*ServerMessage_MetricsRequest) isServerMessage_Payload() {}

// Eski mesaj yapıları (geriye dönük uyumluluk için)
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_AgentInfo
	//	*AgentMessage_QueryResult
	//	*AgentMessage_PostgresInfo
	//	*AgentMessage_SystemMetrics
	//	*AgentMessage_MongoInfo
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_pkg_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetAgentInfo() *AgentInfo {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_AgentInfo); ok {
			return x.AgentInfo
		}
	}
	return nil
}

func (x *AgentMessage) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *AgentMessage) GetPostgresInfo() *PostgresInfo {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_PostgresInfo); ok {
			return x.PostgresInfo
		}
	}
	return nil
}

func (x *AgentMessage) GetSystemMetrics() *SystemMetrics {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SystemMetrics); ok {
			return x.SystemMetrics
		}
	}
	return nil
}

func (x *AgentMessage) GetMongoInfo() *MongoInfo {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_MongoInfo); ok {
			return x.MongoInfo
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_AgentInfo struct {
	AgentInfo *AgentInfo `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3,oneof"`
}

type AgentMessage_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,2,opt,name=query_result,json=queryResult,proto3,oneof"`
}

type AgentMessage_PostgresInfo struct {
	PostgresInfo *PostgresInfo `protobuf:"bytes,3,opt,name=postgres_info,json=postgresInfo,proto3,oneof"`
}

type AgentMessage_SystemMetrics struct {
	SystemMetrics *SystemMetrics `protobuf:"bytes,4,opt,name=system_metrics,json=systemMetrics,proto3,oneof"`
}

type AgentMessage_MongoInfo struct {
	MongoInfo *MongoInfo `protobuf:"bytes,5,opt,name=mongo_info,json=mongoInfo,proto3,oneof"`
}

func (*AgentMessage_AgentInfo) isAgentMessage_Payload() {}

func (*AgentMessage_QueryResult) isAgentMessage_Payload() {}

func (*AgentMessage_PostgresInfo) isAgentMessage_Payload() {}

func (*AgentMessage_SystemMetrics) isAgentMessage_Payload() {}

func (*AgentMessage_MongoInfo) isAgentMessage_Payload() {}

type SystemMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage        float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	LoadAverage_1M  float64                `protobuf:"fixed64,3,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	LoadAverage_5M  float64                `protobuf:"fixed64,4,opt,name=load_average_5m,json=loadAverage5m,proto3" json:"load_average_5m,omitempty"`
	LoadAverage_15M float64                `protobuf:"fixed64,5,opt,name=load_average_15m,json=loadAverage15m,proto3" json:"load_average_15m,omitempty"`
	TotalMemory     int64                  `protobuf:"varint,6,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	FreeMemory      int64                  `protobuf:"varint,7,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	TotalDisk       int64                  `protobuf:"varint,8,opt,name=total_disk,json=totalDisk,proto3" json:"total_disk,omitempty"`
	FreeDisk        int64                  `protobuf:"varint,9,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	CpuCores        int32                  `protobuf:"varint,10,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	OsVersion       string                 `protobuf:"bytes,11,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	KernelVersion   string                 `protobuf:"bytes,12,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Uptime          int64                  `protobuf:"varint,13,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_pkg_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetLoadAverage_1M() float64 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *SystemMetrics) GetLoadAverage_5M() float64 {
	if x != nil {
		return x.LoadAverage_5M
	}
	return 0
}

func (x *SystemMetrics) GetLoadAverage_15M() float64 {
	if x != nil {
		return x.LoadAverage_15M
	}
	return 0
}

func (x *SystemMetrics) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *SystemMetrics) GetFreeMemory() int64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *SystemMetrics) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *SystemMetrics) GetFreeDisk() int64 {
	if x != nil {
		return x.FreeDisk
	}
	return 0
}

func (x *SystemMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemMetrics) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemMetrics) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemMetrics) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type SystemMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetricsRequest) Reset() {
	*x = SystemMetricsRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsRequest) ProtoMessage() {}

func (x *SystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*SystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *SystemMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type SystemMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetricsResponse) Reset() {
	*x = SystemMetricsResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsResponse) ProtoMessage() {}

func (x *SystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*SystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{25}
}

func (x *SystemMetricsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SystemMetricsResponse) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Alarm yapılandırmaları için tanımlanan mesajlar
type AlarmConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmConfigRequest) Reset() {
	*x = AlarmConfigRequest{}
	mi := &file_pkg_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmConfigRequest) ProtoMessage() {}

func (x *AlarmConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmConfigRequest.ProtoReflect.Descriptor instead.
func (*AlarmConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *AlarmConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AlarmConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Configurations []*AlarmConfiguration  `protobuf:"bytes,2,rep,name=configurations,proto3" json:"configurations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlarmConfigResponse) Reset() {
	*x = AlarmConfigResponse{}
	mi := &file_pkg_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmConfigResponse) ProtoMessage() {}

func (x *AlarmConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmConfigResponse.ProtoReflect.Descriptor instead.
func (*AlarmConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_agent_proto_rawDescGZIP(), []int{27}
}

func (x *AlarmConfigResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlarmConfigResponse) GetConfigurations() []*AlarmConfiguration {
	if x != nil {
		return x.Configurations
	}
	return nil
}

var File_pkg_agent_agent_proto protoreflect.FileDescriptor

const file_pkg_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/agent/agent.proto\x12\x05agent\x1a\x19google/protobuf/any.proto\"\xf2\x01\n" +
	"\tAgentInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x12\n" +
	"\x04auth\x18\x06 \x01(\bR\x04auth\x12\x12\n" +
	"\x04test\x18\a \x01(\tR\x04test\x12#\n" +
	"\rpostgres_user\x18\b \x01(\tR\fpostgresUser\x12#\n" +
	"\rpostgres_pass\x18\t \x01(\tR\fpostgresPass\"\xfd\x02\n" +
	"\fPostgresInfo\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vnode_status\x18\x04 \x01(\tR\n" +
	"nodeStatus\x12\x1d\n" +
	"\n" +
	"pg_version\x18\x05 \x01(\tR\tpgVersion\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12*\n" +
	"\x11pg_bouncer_status\x18\a \x01(\tR\x0fpgBouncerStatus\x12*\n" +
	"\x11pg_service_status\x18\b \x01(\tR\x0fpgServiceStatus\x12.\n" +
	"\x13replication_lag_sec\x18\t \x01(\x03R\x11replicationLagSec\x12\x1b\n" +
	"\tfree_disk\x18\n" +
	" \x01(\tR\bfreeDisk\x12\x1d\n" +
	"\n" +
	"fd_percent\x18\v \x01(\x05R\tfdPercent\"\xf5\x02\n" +
	"\tMongoInfo\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vnode_status\x18\x04 \x01(\tR\n" +
	"nodeStatus\x12#\n" +
	"\rmongo_version\x18\x05 \x01(\tR\fmongoVersion\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12!\n" +
	"\fmongo_status\x18\a \x01(\tR\vmongoStatus\x12(\n" +
	"\x10replica_set_name\x18\b \x01(\tR\x0ereplicaSetName\x12.\n" +
	"\x13replication_lag_sec\x18\t \x01(\x03R\x11replicationLagSec\x12\x1b\n" +
	"\tfree_disk\x18\n" +
	" \x01(\tR\bfreeDisk\x12\x1d\n" +
	"\n" +
	"fd_percent\x18\v \x01(\x05R\tfdPercent\"\x8d\x01\n" +
	"\x0eAlarmCondition\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\tR\tthreshold\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"\xda\x01\n" +
	"\x12AlarmConfiguration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x123\n" +
	"\tcondition\x18\x05 \x01(\v2\x15.agent.AlarmConditionR\tcondition\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1a\n" +
	"\bchannels\x18\a \x03(\tR\bchannels\"\x82\x02\n" +
	"\n" +
	"AlarmEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\balarm_id\x18\x02 \x01(\tR\aalarmId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vmetric_name\x18\x05 \x01(\tR\n" +
	"metricName\x12!\n" +
	"\fmetric_value\x18\x06 \x01(\tR\vmetricValue\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\"<\n" +
	"\x05Query\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"V\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12,\n" +
	"\x06result\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06result\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12RegistrationResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x12ReportAlarmRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x06events\x18\x02 \x03(\v2\x11.agent.AlarmEventR\x06events\"-\n" +
	"\x13ReportAlarmResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"B\n" +
	"\x0fRegisterRequest\x12/\n" +
	"\n" +
	"agent_info\x18\x01 \x01(\v2\x10.agent.AgentInfoR\tagentInfo\"Q\n" +
	"\x10RegisterResponse\x12=\n" +
	"\fregistration\x18\x01 \x01(\v2\x19.agent.RegistrationResultR\fregistration\"2\n" +
	"\fQueryRequest\x12\"\n" +
	"\x05query\x18\x01 \x01(\v2\f.agent.QueryR\x05query\";\n" +
	"\rQueryResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.agent.QueryResultR\x06result\"O\n" +
	"\x13PostgresInfoRequest\x128\n" +
	"\rpostgres_info\x18\x01 \x01(\v2\x13.agent.PostgresInfoR\fpostgresInfo\"C\n" +
	"\x10MongoInfoRequest\x12/\n" +
	"\n" +
	"mongo_info\x18\x01 \x01(\v2\x10.agent.MongoInfoR\tmongoInfo\".\n" +
	"\x14PostgresInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"+\n" +
	"\x11MongoInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"3\n" +
	"\rErrorResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.agent.ErrorR\x05error\"\xef\x01\n" +
	"\rServerMessage\x12$\n" +
	"\x05query\x18\x01 \x01(\v2\f.agent.QueryH\x00R\x05query\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\f.agent.ErrorH\x00R\x05error\x12?\n" +
	"\fregistration\x18\x03 \x01(\v2\x19.agent.RegistrationResultH\x00R\fregistration\x12F\n" +
	"\x0fmetrics_request\x18\x04 \x01(\v2\x1b.agent.SystemMetricsRequestH\x00R\x0emetricsRequestB\t\n" +
	"\apayload\"\xb3\x02\n" +
	"\fAgentMessage\x121\n" +
	"\n" +
	"agent_info\x18\x01 \x01(\v2\x10.agent.AgentInfoH\x00R\tagentInfo\x127\n" +
	"\fquery_result\x18\x02 \x01(\v2\x12.agent.QueryResultH\x00R\vqueryResult\x12:\n" +
	"\rpostgres_info\x18\x03 \x01(\v2\x13.agent.PostgresInfoH\x00R\fpostgresInfo\x12=\n" +
	"\x0esystem_metrics\x18\x04 \x01(\v2\x14.agent.SystemMetricsH\x00R\rsystemMetrics\x121\n" +
	"\n" +
	"mongo_info\x18\x05 \x01(\v2\x10.agent.MongoInfoH\x00R\tmongoInfoB\t\n" +
	"\apayload\"\xc4\x03\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12&\n" +
	"\x0fload_average_1m\x18\x03 \x01(\x01R\rloadAverage1m\x12&\n" +
	"\x0fload_average_5m\x18\x04 \x01(\x01R\rloadAverage5m\x12(\n" +
	"\x10load_average_15m\x18\x05 \x01(\x01R\x0eloadAverage15m\x12!\n" +
	"\ftotal_memory\x18\x06 \x01(\x03R\vtotalMemory\x12\x1f\n" +
	"\vfree_memory\x18\a \x01(\x03R\n" +
	"freeMemory\x12\x1d\n" +
	"\n" +
	"total_disk\x18\b \x01(\x03R\ttotalDisk\x12\x1b\n" +
	"\tfree_disk\x18\t \x01(\x03R\bfreeDisk\x12\x1b\n" +
	"\tcpu_cores\x18\n" +
	" \x01(\x05R\bcpuCores\x12\x1d\n" +
	"\n" +
	"os_version\x18\v \x01(\tR\tosVersion\x12%\n" +
	"\x0ekernel_version\x18\f \x01(\tR\rkernelVersion\x12\x16\n" +
	"\x06uptime\x18\r \x01(\x03R\x06uptime\"1\n" +
	"\x14SystemMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"_\n" +
	"\x15SystemMetricsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12.\n" +
	"\ametrics\x18\x02 \x01(\v2\x14.agent.SystemMetricsR\ametrics\"/\n" +
	"\x12AlarmConfigRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"p\n" +
	"\x13AlarmConfigResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12A\n" +
	"\x0econfigurations\x18\x02 \x03(\v2\x19.agent.AlarmConfigurationR\x0econfigurations2\xcb\x05\n" +
	"\fAgentService\x128\n" +
	"\aConnect\x12\x13.agent.AgentMessage\x1a\x14.agent.ServerMessage(\x010\x01\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x129\n" +
	"\fExecuteQuery\x12\x13.agent.QueryRequest\x1a\x14.agent.QueryResponse\x12K\n" +
	"\x10SendPostgresInfo\x12\x1a.agent.PostgresInfoRequest\x1a\x1b.agent.PostgresInfoResponse\x12>\n" +
	"\rStreamQueries\x12\x13.agent.QueryRequest\x1a\x14.agent.QueryResponse(\x010\x01\x12Q\n" +
	"\x12StreamPostgresInfo\x12\x1a.agent.PostgresInfoRequest\x1a\x1b.agent.PostgresInfoResponse(\x010\x01\x12N\n" +
	"\x11SendSystemMetrics\x12\x1b.agent.SystemMetricsRequest\x1a\x1c.agent.SystemMetricsResponse\x12O\n" +
	"\x16GetAlarmConfigurations\x12\x19.agent.AlarmConfigRequest\x1a\x1a.agent.AlarmConfigResponse\x12D\n" +
	"\vReportAlarm\x12\x19.agent.ReportAlarmRequest\x1a\x1a.agent.ReportAlarmResponse\x12B\n" +
	"\rSendMongoInfo\x12\x17.agent.MongoInfoRequest\x1a\x18.agent.MongoInfoResponseB0Z.github.com/sefaphlvn/clustereye-test/pkg/agentb\x06proto3"

var (
	file_pkg_agent_agent_proto_rawDescOnce sync.Once
	file_pkg_agent_agent_proto_rawDescData []byte
)

func file_pkg_agent_agent_proto_rawDescGZIP() []byte {
	file_pkg_agent_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_agent_proto_rawDesc), len(file_pkg_agent_agent_proto_rawDesc)))
	})
	return file_pkg_agent_agent_proto_rawDescData
}

var file_pkg_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pkg_agent_agent_proto_goTypes = []any{
	(*AgentInfo)(nil),             // 0: agent.AgentInfo
	(*PostgresInfo)(nil),          // 1: agent.PostgresInfo
	(*MongoInfo)(nil),             // 2: agent.MongoInfo
	(*AlarmCondition)(nil),        // 3: agent.AlarmCondition
	(*AlarmConfiguration)(nil),    // 4: agent.AlarmConfiguration
	(*AlarmEvent)(nil),            // 5: agent.AlarmEvent
	(*Query)(nil),                 // 6: agent.Query
	(*QueryResult)(nil),           // 7: agent.QueryResult
	(*Error)(nil),                 // 8: agent.Error
	(*RegistrationResult)(nil),    // 9: agent.RegistrationResult
	(*ReportAlarmRequest)(nil),    // 10: agent.ReportAlarmRequest
	(*ReportAlarmResponse)(nil),   // 11: agent.ReportAlarmResponse
	(*RegisterRequest)(nil),       // 12: agent.RegisterRequest
	(*RegisterResponse)(nil),      // 13: agent.RegisterResponse
	(*QueryRequest)(nil),          // 14: agent.QueryRequest
	(*QueryResponse)(nil),         // 15: agent.QueryResponse
	(*PostgresInfoRequest)(nil),   // 16: agent.PostgresInfoRequest
	(*MongoInfoRequest)(nil),      // 17: agent.MongoInfoRequest
	(*PostgresInfoResponse)(nil),  // 18: agent.PostgresInfoResponse
	(*MongoInfoResponse)(nil),     // 19: agent.MongoInfoResponse
	(*ErrorResponse)(nil),         // 20: agent.ErrorResponse
	(*ServerMessage)(nil),         // 21: agent.ServerMessage
	(*AgentMessage)(nil),          // 22: agent.AgentMessage
	(*SystemMetrics)(nil),         // 23: agent.SystemMetrics
	(*SystemMetricsRequest)(nil),  // 24: agent.SystemMetricsRequest
	(*SystemMetricsResponse)(nil), // 25: agent.SystemMetricsResponse
	(*AlarmConfigRequest)(nil),    // 26: agent.AlarmConfigRequest
	(*AlarmConfigResponse)(nil),   // 27: agent.AlarmConfigResponse
	(*any1.Any)(nil),              // 28: google.protobuf.Any
}
var file_pkg_agent_agent_proto_depIdxs = []int32{
	3,  // 0: agent.AlarmConfiguration.condition:type_name -> agent.AlarmCondition
	28, // 1: agent.QueryResult.result:type_name -> google.protobuf.Any
	5,  // 2: agent.ReportAlarmRequest.events:type_name -> agent.AlarmEvent
	0,  // 3: agent.RegisterRequest.agent_info:type_name -> agent.AgentInfo
	9,  // 4: agent.RegisterResponse.registration:type_name -> agent.RegistrationResult
	6,  // 5: agent.QueryRequest.query:type_name -> agent.Query
	7,  // 6: agent.QueryResponse.result:type_name -> agent.QueryResult
	1,  // 7: agent.PostgresInfoRequest.postgres_info:type_name -> agent.PostgresInfo
	2,  // 8: agent.MongoInfoRequest.mongo_info:type_name -> agent.MongoInfo
	8,  // 9: agent.ErrorResponse.error:type_name -> agent.Error
	6,  // 10: agent.ServerMessage.query:type_name -> agent.Query
	8,  // 11: agent.ServerMessage.error:type_name -> agent.Error
	9,  // 12: agent.ServerMessage.registration:type_name -> agent.RegistrationResult
	24, // 13: agent.ServerMessage.metrics_request:type_name -> agent.SystemMetricsRequest
	0,  // 14: agent.AgentMessage.agent_info:type_name -> agent.AgentInfo
	7,  // 15: agent.AgentMessage.query_result:type_name -> agent.QueryResult
	1,  // 16: agent.AgentMessage.postgres_info:type_name -> agent.PostgresInfo
	23, // 17: agent.AgentMessage.system_metrics:type_name -> agent.SystemMetrics
	2,  // 18: agent.AgentMessage.mongo_info:type_name -> agent.MongoInfo
	23, // 19: agent.SystemMetricsResponse.metrics:type_name -> agent.SystemMetrics
	4,  // 20: agent.AlarmConfigResponse.configurations:type_name -> agent.AlarmConfiguration
	22, // 21: agent.AgentService.Connect:input_type -> agent.AgentMessage
	12, // 22: agent.AgentService.Register:input_type -> agent.RegisterRequest
	14, // 23: agent.AgentService.ExecuteQuery:input_type -> agent.QueryRequest
	16, // 24: agent.AgentService.SendPostgresInfo:input_type -> agent.PostgresInfoRequest
	14, // 25: agent.AgentService.StreamQueries:input_type -> agent.QueryRequest
	16, // 26: agent.AgentService.StreamPostgresInfo:input_type -> agent.PostgresInfoRequest
	24, // 27: agent.AgentService.SendSystemMetrics:input_type -> agent.SystemMetricsRequest
	26, // 28: agent.AgentService.GetAlarmConfigurations:input_type -> agent.AlarmConfigRequest
	10, // 29: agent.AgentService.ReportAlarm:input_type -> agent.ReportAlarmRequest
	17, // 30: agent.AgentService.SendMongoInfo:input_type -> agent.MongoInfoRequest
	21, // 31: agent.AgentService.Connect:output_type -> agent.ServerMessage
	13, // 32: agent.AgentService.Register:output_type -> agent.RegisterResponse
	15, // 33: agent.AgentService.ExecuteQuery:output_type -> agent.QueryResponse
	18, // 34: agent.AgentService.SendPostgresInfo:output_type -> agent.PostgresInfoResponse
	15, // 35: agent.AgentService.StreamQueries:output_type -> agent.QueryResponse
	18, // 36: agent.AgentService.StreamPostgresInfo:output_type -> agent.PostgresInfoResponse
	25, // 37: agent.AgentService.SendSystemMetrics:output_type -> agent.SystemMetricsResponse
	27, // 38: agent.AgentService.GetAlarmConfigurations:output_type -> agent.AlarmConfigResponse
	11, // 39: agent.AgentService.ReportAlarm:output_type -> agent.ReportAlarmResponse
	19, // 40: agent.AgentService.SendMongoInfo:output_type -> agent.MongoInfoResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pkg_agent_agent_proto_init() }
func file_pkg_agent_agent_proto_init() {
	if File_pkg_agent_agent_proto != nil {
		return
	}
	file_pkg_agent_agent_proto_msgTypes[21].OneofWrappers = []any{
		(*ServerMessage_Query)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Registration)(nil),
		(*ServerMessage_MetricsRequest)(nil),
	}
	file_pkg_agent_agent_proto_msgTypes[22].OneofWrappers = []any{
		(*AgentMessage_AgentInfo)(nil),
		(*AgentMessage_QueryResult)(nil),
		(*AgentMessage_PostgresInfo)(nil),
		(*AgentMessage_SystemMetrics)(nil),
		(*AgentMessage_MongoInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_agent_proto_rawDesc), len(file_pkg_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agent_agent_proto_depIdxs,
		MessageInfos:      file_pkg_agent_agent_proto_msgTypes,
	}.Build()
	File_pkg_agent_agent_proto = out.File
	file_pkg_agent_agent_proto_goTypes = nil
	file_pkg_agent_agent_proto_depIdxs = nil
}
