// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: agent.proto

package agent

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Auth          bool                   `protobuf:"varint,6,opt,name=auth,proto3" json:"auth,omitempty"`
	Test          string                 `protobuf:"bytes,7,opt,name=test,proto3" json:"test,omitempty"`
	PostgresUser  string                 `protobuf:"bytes,8,opt,name=postgres_user,json=postgresUser,proto3" json:"postgres_user,omitempty"`
	PostgresPass  string                 `protobuf:"bytes,9,opt,name=postgres_pass,json=postgresPass,proto3" json:"postgres_pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentInfo) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *AgentInfo) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

func (x *AgentInfo) GetPostgresUser() string {
	if x != nil {
		return x.PostgresUser
	}
	return ""
}

func (x *AgentInfo) GetPostgresPass() string {
	if x != nil {
		return x.PostgresPass
	}
	return ""
}

type PostgresInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterName       string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Ip                string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname          string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeStatus        string                 `protobuf:"bytes,4,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	PgVersion         string                 `protobuf:"bytes,5,opt,name=pg_version,json=pgVersion,proto3" json:"pg_version,omitempty"`
	Location          string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	PgBouncerStatus   string                 `protobuf:"bytes,7,opt,name=pg_bouncer_status,json=pgBouncerStatus,proto3" json:"pg_bouncer_status,omitempty"`
	PgServiceStatus   string                 `protobuf:"bytes,8,opt,name=pg_service_status,json=pgServiceStatus,proto3" json:"pg_service_status,omitempty"`
	ReplicationLagSec int64                  `protobuf:"varint,9,opt,name=replication_lag_sec,json=replicationLagSec,proto3" json:"replication_lag_sec,omitempty"`
	FreeDisk          string                 `protobuf:"bytes,10,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	FdPercent         int32                  `protobuf:"varint,11,opt,name=fd_percent,json=fdPercent,proto3" json:"fd_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostgresInfo) Reset() {
	*x = PostgresInfo{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfo) ProtoMessage() {}

func (x *PostgresInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfo.ProtoReflect.Descriptor instead.
func (*PostgresInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *PostgresInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PostgresInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PostgresInfo) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *PostgresInfo) GetPgVersion() string {
	if x != nil {
		return x.PgVersion
	}
	return ""
}

func (x *PostgresInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PostgresInfo) GetPgBouncerStatus() string {
	if x != nil {
		return x.PgBouncerStatus
	}
	return ""
}

func (x *PostgresInfo) GetPgServiceStatus() string {
	if x != nil {
		return x.PgServiceStatus
	}
	return ""
}

func (x *PostgresInfo) GetReplicationLagSec() int64 {
	if x != nil {
		return x.ReplicationLagSec
	}
	return 0
}

func (x *PostgresInfo) GetFreeDisk() string {
	if x != nil {
		return x.FreeDisk
	}
	return ""
}

func (x *PostgresInfo) GetFdPercent() int32 {
	if x != nil {
		return x.FdPercent
	}
	return 0
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *Query) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Result        *any1.Any              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetResult() *any1.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegistrationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResult) Reset() {
	*x = RegistrationResult{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResult) ProtoMessage() {}

func (x *RegistrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResult.ProtoReflect.Descriptor instead.
func (*RegistrationResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sadece agent kaydı için kullanılacak mesajlar
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentInfo     *AgentInfo             `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *RegistrationResult    `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetRegistration() *RegistrationResult {
	if x != nil {
		return x.Registration
	}
	return nil
}

// Query için kullanılacak mesajlar
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *QueryResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// PostgreSQL bilgileri için kullanılacak mesajlar
type PostgresInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostgresInfo  *PostgresInfo          `protobuf:"bytes,1,opt,name=postgres_info,json=postgresInfo,proto3" json:"postgres_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresInfoRequest) Reset() {
	*x = PostgresInfoRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfoRequest) ProtoMessage() {}

func (x *PostgresInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfoRequest.ProtoReflect.Descriptor instead.
func (*PostgresInfoRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PostgresInfoRequest) GetPostgresInfo() *PostgresInfo {
	if x != nil {
		return x.PostgresInfo
	}
	return nil
}

type PostgresInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresInfoResponse) Reset() {
	*x = PostgresInfoResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresInfoResponse) ProtoMessage() {}

func (x *PostgresInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresInfoResponse.ProtoReflect.Descriptor instead.
func (*PostgresInfoResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PostgresInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Genel hata mesajı
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x19google/protobuf/any.proto\"\xf2\x01\n" +
	"\tAgentInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x12\n" +
	"\x04auth\x18\x06 \x01(\bR\x04auth\x12\x12\n" +
	"\x04test\x18\a \x01(\tR\x04test\x12#\n" +
	"\rpostgres_user\x18\b \x01(\tR\fpostgresUser\x12#\n" +
	"\rpostgres_pass\x18\t \x01(\tR\fpostgresPass\"\xfd\x02\n" +
	"\fPostgresInfo\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vnode_status\x18\x04 \x01(\tR\n" +
	"nodeStatus\x12\x1d\n" +
	"\n" +
	"pg_version\x18\x05 \x01(\tR\tpgVersion\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12*\n" +
	"\x11pg_bouncer_status\x18\a \x01(\tR\x0fpgBouncerStatus\x12*\n" +
	"\x11pg_service_status\x18\b \x01(\tR\x0fpgServiceStatus\x12.\n" +
	"\x13replication_lag_sec\x18\t \x01(\x03R\x11replicationLagSec\x12\x1b\n" +
	"\tfree_disk\x18\n" +
	" \x01(\tR\bfreeDisk\x12\x1d\n" +
	"\n" +
	"fd_percent\x18\v \x01(\x05R\tfdPercent\"<\n" +
	"\x05Query\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"V\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12,\n" +
	"\x06result\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06result\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12RegistrationResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x0fRegisterRequest\x12/\n" +
	"\n" +
	"agent_info\x18\x01 \x01(\v2\x10.agent.AgentInfoR\tagentInfo\"Q\n" +
	"\x10RegisterResponse\x12=\n" +
	"\fregistration\x18\x01 \x01(\v2\x19.agent.RegistrationResultR\fregistration\"2\n" +
	"\fQueryRequest\x12\"\n" +
	"\x05query\x18\x01 \x01(\v2\f.agent.QueryR\x05query\";\n" +
	"\rQueryResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.agent.QueryResultR\x06result\"O\n" +
	"\x13PostgresInfoRequest\x128\n" +
	"\rpostgres_info\x18\x01 \x01(\v2\x13.agent.PostgresInfoR\fpostgresInfo\".\n" +
	"\x14PostgresInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"3\n" +
	"\rErrorResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.agent.ErrorR\x05error2\xe6\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x129\n" +
	"\fExecuteQuery\x12\x13.agent.QueryRequest\x1a\x14.agent.QueryResponse\x12K\n" +
	"\x10SendPostgresInfo\x12\x1a.agent.PostgresInfoRequest\x1a\x1b.agent.PostgresInfoResponse\x12>\n" +
	"\rStreamQueries\x12\x13.agent.QueryRequest\x1a\x14.agent.QueryResponse(\x010\x01\x12Q\n" +
	"\x12StreamPostgresInfo\x12\x1a.agent.PostgresInfoRequest\x1a\x1b.agent.PostgresInfoResponse(\x010\x01B0Z.github.com/sefaphlvn/clustereye-test/pkg/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(*AgentInfo)(nil),            // 0: agent.AgentInfo
	(*PostgresInfo)(nil),         // 1: agent.PostgresInfo
	(*Query)(nil),                // 2: agent.Query
	(*QueryResult)(nil),          // 3: agent.QueryResult
	(*Error)(nil),                // 4: agent.Error
	(*RegistrationResult)(nil),   // 5: agent.RegistrationResult
	(*RegisterRequest)(nil),      // 6: agent.RegisterRequest
	(*RegisterResponse)(nil),     // 7: agent.RegisterResponse
	(*QueryRequest)(nil),         // 8: agent.QueryRequest
	(*QueryResponse)(nil),        // 9: agent.QueryResponse
	(*PostgresInfoRequest)(nil),  // 10: agent.PostgresInfoRequest
	(*PostgresInfoResponse)(nil), // 11: agent.PostgresInfoResponse
	(*ErrorResponse)(nil),        // 12: agent.ErrorResponse
	(*any1.Any)(nil),             // 13: google.protobuf.Any
}
var file_agent_proto_depIdxs = []int32{
	13, // 0: agent.QueryResult.result:type_name -> google.protobuf.Any
	0,  // 1: agent.RegisterRequest.agent_info:type_name -> agent.AgentInfo
	5,  // 2: agent.RegisterResponse.registration:type_name -> agent.RegistrationResult
	2,  // 3: agent.QueryRequest.query:type_name -> agent.Query
	3,  // 4: agent.QueryResponse.result:type_name -> agent.QueryResult
	1,  // 5: agent.PostgresInfoRequest.postgres_info:type_name -> agent.PostgresInfo
	4,  // 6: agent.ErrorResponse.error:type_name -> agent.Error
	6,  // 7: agent.AgentService.Register:input_type -> agent.RegisterRequest
	8,  // 8: agent.AgentService.ExecuteQuery:input_type -> agent.QueryRequest
	10, // 9: agent.AgentService.SendPostgresInfo:input_type -> agent.PostgresInfoRequest
	8,  // 10: agent.AgentService.StreamQueries:input_type -> agent.QueryRequest
	10, // 11: agent.AgentService.StreamPostgresInfo:input_type -> agent.PostgresInfoRequest
	7,  // 12: agent.AgentService.Register:output_type -> agent.RegisterResponse
	9,  // 13: agent.AgentService.ExecuteQuery:output_type -> agent.QueryResponse
	11, // 14: agent.AgentService.SendPostgresInfo:output_type -> agent.PostgresInfoResponse
	9,  // 15: agent.AgentService.StreamQueries:output_type -> agent.QueryResponse
	11, // 16: agent.AgentService.StreamPostgresInfo:output_type -> agent.PostgresInfoResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
